# Generated by Django 6.0.3 on 2026-04-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
