# Generated by Django 6.0.3 on 2026-04-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20260401_0259"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Wallet", "verbose_name_plural": "Wallets"},
        ),
    ]
