# Generated by Django 6.0.3 on 2026-04-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Commission rate in percentage (e.g., 10 = 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("per_order", "Per Order"),
                            ("per_pharmacy", "Per Pharmacy"),
                            ("per_month", "Per Month"),
                        ],
                        default="per_order",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
