# Generated by Django 4.2.29 on 2026-04-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("deliveries", "0002_initial"),
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="riders.rider",
            ),
        ),
    ]
